from .kimodo_nodes import NODE_CLASS_MAPPINGS as _BVH_NODES, NODE_DISPLAY_NAME_MAPPINGS as _BVH_NAMES
from .kimodo_fbx_nodes import NODE_CLASS_MAPPINGS as _FBX_NODES, NODE_DISPLAY_NAME_MAPPINGS as _FBX_NAMES

NODE_CLASS_MAPPINGS = {**_BVH_NODES, **_FBX_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_BVH_NAMES, **_FBX_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
